### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by maplepy** [42-tronc/minishell#114]
```
minishell> ls > out | < out cat

minishell: syntax error near unexpected token `<'
=================================================================
==223030==ERROR: AddressSanitizer: attempting double-free on 0x606000000380 in thread T0:
    #0 0x7efe02edfdc2 in __interceptor_free /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:52
    #1 0x556c73940927 in main (/home/maplepy/git/cc/minishell/minishell+0x3927) (BuildId: 1070cfbbb45c1bb29b9cff80c9b71967ffc86d9a)
    #2 0x7efe02c3984f  (/usr/lib/libc.so.6+0x2384f) (BuildId: 2f005a79cd1a8e385972f5a102f16adba414d75e)
    #3 0x7efe02c39909 in __libc_start_main (/usr/lib/libc.so.6+0x23909) (BuildId: 2f005a79cd1a8e385972f5a102f16adba414d75e)
    #4 0x556c7393e234 in _start (/home/maplepy/git/cc/minishell/minishell+0x1234) (BuildId: 1070cfbbb45c1bb29b9cff80c9b71967ffc86d9a)

0x606000000380 is located 0 bytes inside of 64-byte region [0x606000000380,0x6060000003c0)
freed by thread T0 here:
    #0 0x7efe02edfdc2 in __interceptor_free /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:52
    #1 0x556c73942494 in prepare_token (/home/maplepy/git/cc/minishell/minishell+0x5494) (BuildId: 1070cfbbb45c1bb29b9cff80c9b71967ffc86d9a)
    #2 0x556c739408d2 in main (/home/maplepy/git/cc/minishell/minishell+0x38d2) (BuildId: 1070cfbbb45c1bb29b9cff80c9b71967ffc86d9a)
    #3 0x7efe02c3984f  (/usr/lib/libc.so.6+0x2384f) (BuildId: 2f005a79cd1a8e385972f5a102f16adba414d75e)

previously allocated by thread T0 here:
    #0 0x7efe02ee1369 in __interceptor_malloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x556c73942f3e in ft_calloc (/home/maplepy/git/cc/minishell/minishell+0x5f3e) (BuildId: 1070cfbbb45c1bb29b9cff80c9b71967ffc86d9a)
    #2 0x556c739414b9 in getting_line (/home/maplepy/git/cc/minishell/minishell+0x44b9) (BuildId: 1070cfbbb45c1bb29b9cff80c9b71967ffc86d9a)
    #3 0x556c739408b1 in main (/home/maplepy/git/cc/minishell/minishell+0x38b1) (BuildId: 1070cfbbb45c1bb29b9cff80c9b71967ffc86d9a)
    #4 0x7efe02c3984f  (/usr/lib/libc.so.6+0x2384f) (BuildId: 2f005a79cd1a8e385972f5a102f16adba414d75e)

SUMMARY: AddressSanitizer: double-free /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:52 in __interceptor_free
==223030==ABORTING
```

ca devrait marcher ca

**Comment by maplepy** [comment]
mici
